### ISSUE TITLE
Fix MP's company CC & pay bills

### ISSUE THREAD

**Issue by mipearson** [mipearson/cardstmp#101]
Invoices are bouncing because something's gone weird with my CC and Internet purchases. I need to call NAB and sort it out.
## TODO

 - [x] Call NAB
 - [x] Pay dnsimple with AMEX
 - [x] Pay github with AMEX
 - [ ] Receive new card & change PIN
 - [ ] Identify recurring services to switch
 - [ ] Switch AWS
 - [ ] Switch Pingdom
 - [ ] Switch Hetzner.DE
 - [ ] Librato
 - [ ] Gmail?
 - [x] Flowdock
 - [ ] Bugherd (cancel?)
