### ISSUE TITLE
Fix billing bracket costs for US

### ISSUE THREAD

**Issue by mipearson** [mipearson/cardstmp#103]
Set the Value of Enquiry bracket rates as so:

```
0 - 5000 			   $79
50001 - 10000 	$149
10001 - 20000	 	$199
20001 - 30000       $299
then 1% of every $100
```

Set it so that the signup fee is $1.

VoE brackets & subscription costs can be set directly on the production database using SQL.
## TODO

 - [x] Set VoE brackets in database
 - [x] Set subscription cost for VoE subscription to $1 (So first month is $1)
 - [x] Ensure tax rate for this is 0% (as it's a service, and not taxed)
 - [x] Ensure tax is not mentioned on pricing table or signup process
