### ISSUE TITLE
Remove plaintext passwords for retailers

### ISSUE THREAD

**Issue by mipearson** [mipearson/cardstmp#105]
Out of scope: admin passwords.

Don't want to use devise gem.
## TODO

 - [ ] encryption method - consider bcrypt
 - [ ] password reset - email slug, user to set new password
 - [ ] ability for admins to change passwords
 - [ ] migration to encrypt current passwords
