### ISSUE TITLE
Fix teg dashboard javascript

### ISSUE THREAD

**Issue by mipearson** [mipearson/cardstmp#118]
## TODO

 - [x] Confirm that long-running timeouts are fixed by switching from thin to puma.
 - [x] Remove animations so that it doesn't chug on Android or RPi browsers
 - [x] Auto-refresh either every 30 mins or when server is restarted so that we can update the HTML without having to manually refresh the page
