### ISSUE TITLE
Renew certificates

### ISSUE THREAD

**Issue by mipearson** [mipearson/cardstmp#133]
## TODO

 - [x] Identify certs soon to expire
 - [x] script to check certificate expiry
 - [x] renoexchange.com.au
 - [x] bikeexchange.co.nz
 - [x] Remove old expired bikexchange.com.au cert
 - [x] Push to office
 - [x] Push to prod
